[pytest]
minversion = 7.0
django_find_project = false
pythonpath =
    .
    blogicum

DJANGO_SETTINGS_MODULE = blogicum.blogicum.settings
norecursedirs = env venv .venv
addopts = -rE -vv --show-capture=no --disable-warnings -p no:cacheprovider
testpaths = tests/
python_files = test_*.py
django_debug_mode = true
