[pytest]
# Проект Django находится в каталоге blogicum/ относительно этого файла.
# Добавляем и корень репозитория, и каталог проекта в sys.path.
minversion = 7.0
pythonpath = ./blogicum
django_find_project = true
DJANGO_SETTINGS_MODULE = blogicum.settings
norecursedirs = env venv .venv
addopts = -rE -vv --show-capture=no --disable-warnings -p no:cacheprovider
testpaths = tests/
python_files = test_*.py
django_debug_mode = true
