# Generated by Django 3.2.16 on 2026-04-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = []
